
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 22 14:14:26 CEST 2024
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 45;
  public static final int DISTINTO = 16;
  public static final int FUNCTION = 25;
  public static final int CONST = 35;
  public static final int POR = 6;
  public static final int PUNTO_Y_COMA = 10;
  public static final int CIERRA_PARENTESIS = 18;
  public static final int INTEGER = 38;
  public static final int DOS_PUNTOS = 11;
  public static final int REPEAT = 31;
  public static final int RANGO = 14;
  public static final int ABRE_PARENTESIS = 17;
  public static final int MINUS = 3;
  public static final int WRITE = 44;
  public static final int ABRE_VECTOR = 19;
  public static final int IDENTIFICADOR = 47;
  public static final int IGUAL = 12;
  public static final int TYPE = 33;
  public static final int OR = 43;
  public static final int IN = 41;
  public static final int CIERRA_VECTOR = 20;
  public static final int CIERRA_CORCHETE = 22;
  public static final int BEGIN = 23;
  public static final int UNTIL = 32;
  public static final int PLUS = 2;
  public static final int IF = 28;
  public static final int OF = 42;
  public static final int BOOLEAN = 37;
  public static final int EOF = 0;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int PROGRAM = 27;
  public static final int COMA = 9;
  public static final int CADENA = 46;
  public static final int MENOS = 5;
  public static final int ABRE_CORCHETE = 21;
  public static final int ASIGNACION = 13;
  public static final int MAYOR = 15;
  public static final int ELSE = 30;
  public static final int PUNTO = 8;
  public static final int THEN = 29;
  public static final int END = 24;
  public static final int FALSE = 40;
  public static final int ENTRE = 7;
  public static final int VAR = 36;
  public static final int PROCEDURE = 26;
  public static final int SET = 34;
  public static final int MAS = 4;
}

