
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 22 11:51:12 CEST 2024
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DISTINTO = 14;
  public static final int FUNCTION = 23;
  public static final int CONST = 33;
  public static final int POR = 6;
  public static final int PUNTO_Y_COMA = 8;
  public static final int CIERRA_PARENTESIS = 16;
  public static final int INTEGER = 36;
  public static final int DOS_PUNTOS = 9;
  public static final int REPEAT = 29;
  public static final int RANGO = 12;
  public static final int ABRE_PARENTESIS = 15;
  public static final int MINUS = 3;
  public static final int WRITE = 42;
  public static final int ABRE_VECTOR = 17;
  public static final int IGUAL = 10;
  public static final int TYPE = 31;
  public static final int OR = 41;
  public static final int IN = 39;
  public static final int CIERRA_VECTOR = 18;
  public static final int CIERRA_CORCHETE = 20;
  public static final int BEGIN = 21;
  public static final int UNTIL = 30;
  public static final int PLUS = 2;
  public static final int IF = 26;
  public static final int OF = 40;
  public static final int BOOLEAN = 35;
  public static final int EOF = 0;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int PROGRAM = 25;
  public static final int MENOS = 5;
  public static final int ABRE_CORCHETE = 19;
  public static final int ASIGNACION = 11;
  public static final int MAYOR = 13;
  public static final int ELSE = 28;
  public static final int THEN = 27;
  public static final int END = 22;
  public static final int FALSE = 38;
  public static final int ENTRE = 7;
  public static final int VAR = 34;
  public static final int PROCEDURE = 24;
  public static final int SET = 32;
  public static final int MAS = 4;
}

