
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 09 10:20:28 CET 2024
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 40;
  public static final int DISTINTO = 13;
  public static final int FUNCTION = 20;
  public static final int CONST = 30;
  public static final int POR = 4;
  public static final int PUNTO_Y_COMA = 7;
  public static final int CIERRA_PARENTESIS = 15;
  public static final int INTEGER = 33;
  public static final int DOS_PUNTOS = 8;
  public static final int REPEAT = 26;
  public static final int RANGO = 11;
  public static final int ABRE_PARENTESIS = 14;
  public static final int WRITE = 39;
  public static final int ABRE_VECTOR = 16;
  public static final int IDENTIFICADOR = 42;
  public static final int IGUAL = 9;
  public static final int TYPE = 28;
  public static final int OR = 38;
  public static final int IN = 36;
  public static final int CIERRA_VECTOR = 17;
  public static final int BEGIN = 18;
  public static final int UNTIL = 27;
  public static final int IF = 23;
  public static final int OF = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 32;
  public static final int TRUE = 34;
  public static final int error = 1;
  public static final int PROGRAM = 22;
  public static final int COMA = 6;
  public static final int CADENA = 41;
  public static final int MENOS = 3;
  public static final int ASIGNACION = 10;
  public static final int MAYOR = 12;
  public static final int ELSE = 25;
  public static final int PUNTO = 5;
  public static final int THEN = 24;
  public static final int END = 19;
  public static final int FALSE = 35;
  public static final int VAR = 31;
  public static final int PROCEDURE = 21;
  public static final int SET = 29;
  public static final int MAS = 2;
}

